name: Hello World
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Print Hello World
      run: python -c "print('Hello, world!')"